[BUG] fix `AttributeError: 'ExperimentWriter' object has no attribute 'add_figure'` (#1694)
### Description

This PR is a bugfix for #1256.

At present, the `AttributeError` is raised (and the script exits) if the
logger used does not have the `add_figure` method.

This fix adds a simple check prior to calling `add_figure`.